# Generated by Django 4.2.7 on 2026-10-05 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.CharField(choices=[('FIRST', 'First Semester'), ('SECOND', 'Second Semester'), ('THIRD', 'Third Semester'), ('FOURTH', 'Fourth Semester'), ('FIFTH', 'Fifth Semester'), ('SIXTH', 'Sixth Semester'), ('SEVENTH', 'Seventh Semester'), ('EIGHTH', 'Eighth Semester')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_calendars_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-academic_year', 'semester'],
                'unique_together': {('academic_year', 'semester', 'status')},
            },
        ),
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('EXAMINATION', 'Examination'), ('QUIZ_TEST', 'Quiz / Test'), ('ASSIGNMENT', 'Assignment'), ('HOLIDAY', 'Holiday'), ('PROJECT_MILESTONE', 'Project Milestone'), ('SEMINAR_WORKSHOP', 'Seminar / Workshop'), ('COLLEGE_EVENT', 'College Event'), ('PARENT_TEACHER_MEETING', 'Parent-Teacher Meeting'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('IMPORTANT', 'Important'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.academiccalendar')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
